//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class news
    {
        public int id { get; set; }
        public string titlenew { get; set; }
        public string TexteNews1 { get; set; }
        public string TexteNews2 { get; set; }
        public string image1 { get; set; }
        public string image2 { get; set; }
    }
}
